import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from './component/Header';
import Footer from './component/Footer';
import { Work_Sans } from 'next/font/google'

// Load Google fonts with CSS variable names
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const workSans = Work_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-work-sans',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={workSans.variable}>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen pt-10`}
        suppressHydrationWarning
      >
        <Header />
        <main className="pt-16 flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
